apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default 8080 .Values.service.targetPort }}
      protocol: TCP
      name: {{ default "http" .Values.service.portName }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
