{{- if and (empty .Values.configFilePath | not) (empty .Values.config | not)  }} 
{{ $extension := include  "chart.extension" . }}
{{if or (eq ($extension | upper) "PROPERTIES") (eq ($extension | upper) "ENV") }}
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ template "chart.fullname" . }}
data:
  config: |- 
   {{- range $key, $value:=.Values.config }}
   {{- printf "%s=%s" $key $value | nindent 4 }}
   {{- end }}
{{- end }}
{{- end }}
